services:
  leantime-dev:
    volumes:
      - "${PWD}:/var/www/html"
      - "${PWD}/.dev/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "${PWD}/.dev/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
      - "${PWD}/.dev/test.env:/var/www/html/config/.env"

  db:
    environment:
      MYSQL_DATABASE: leantime_test
    ports:
      - 3307:3306
