x-tool-service: &tool-service
  profiles: ["tools"]
  working_dir: "/app"
  volumes:
    - "${PWD}:/app"

services:
  composer:
    <<: *tool-service
    image: composer
    container_name: leantime-composer
    environment:
      COMPOSER_IGNORE_PLATFORM_REQS: 1

  php:
    profiles: ["tools"]
    build: .
    container_name: leantime-php
    working_dir: "/var/www/html"
    volumes:
      - "${PWD}:/var/www/html"
      - "./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"

  npm:
    <<: *tool-service
    container_name: leantime-npm
    image: node:lts-alpine
    entrypoint: ["npm"]

  npx:
    <<: *tool-service
    container_name: leantime-npx
    image: node:lts-alpine
    entrypoint: ["npx"]
